dfs:
  #  path: D:/wanqiao/uploadPath/awards/
  path: /usr/local/wanqiao/uploadPath/
#  domain: http://61.178.27.127:5520/file/
  domain: http://192.168.100.185:80/file/
  ftpIp: 192.168.100.185
  ftpPath: /wanqiao/uploadPath/
  #  ftpPath: D:/wanqiao/uploadPath/awards/
  ftpUserName: ftpuser
  ftpPassword: ftpuser
  ftpPort: 21
# 项目相关配置
wanqiao:
  # 名称
  name: wanqiao
  # 版本
  version: 2.2.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/wanqiao/uploadPath/awards，Linux配置 /home/wanqiao/uploadPath/awards）
  #  profile: D:/wanqiao/uploadPath/awards
  profile: /home/wanqiao/uploadPath/awards
  # 获取ip地址开关
  addressEnabled: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8083
  servlet:
    # 应用的访问路径

    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    basedir: /tmp/tomcat

# 日志配置
logging:
  level:
    com.wanqiao.mogao: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  50MB
      # 设置总上传的文件大小
      max-request-size:  100MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 密码
#    password: 123456
#    password: root
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    username: 386906718@qq.com
    password: ztmzowzjdglibifd
    # 端口号465或587
    port: 587
    from: 386906718@qq.com
    default-encoding: utf-8

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认三天 60*24*3）
  expireTime: 4320

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.wanqiao.mogao.project.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者
  author: zhangguangbin
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.wanqiao.mogao.project.groupperiod
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_

